[tool.poetry]
name = "groupselect-app"
version = "1.1.0"
description = "The GroupSelect App developed by the Sortition Foundation."
authors = ["Philipp C. Verpoort"]
license = "GNU GPL 3"

[tool.poetry.dependencies]
python = "^3.6"
jsonpickle = "^2.1.0"
fbs = "^1.0.3"
PyQt5 = "^5.15.6"
setuptools = "^60.8.1"
openpyxl = "^3.0.9"

[tool.poetry.dev-dependencies]
PyQt5-stubs = "^5.15.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
