[project]
name = "groupselect-app"
version = "2.1.3"
description = "The GroupSelect App developed by the Sortition Foundation."
authors = [
    { name = "Philipp C. Verpoort", email = "pcv@sortitionfoundation.org" }
]
license = "GNU GPL 3"
package-mode = false
requires-python = ">=3.11,<3.12"
dependencies = [
    "base-app",
    "datahandling",
    "groupselect",
    "pandas>=2.3.3,<3.0.0",
]

[tool.uv.sources]
base-app = { git = "https://github.com/sortitionfoundation/base-app/", tag = "v0.2.0" }
datahandling = { git = "https://github.com/sortitionfoundation/datahandling/", tag = "v0.1.0" }
groupselect = { git = "https://github.com/sortitionfoundation/groupselect-lib", tag = "v0.4.0" }

[dependency-groups]
deployment = [
    "nuitka==2.7.11",
    "ordered-set>=4.1.0",
    "patchelf>=0.17.2.4; sys_platform == 'linux'",
    "pip>=26.0.1",
    "pip-licenses>=5.5.1",
    "setuptools>=81.0.0",
    "wheel>=0.46.3",
    "zstandard>=0.25.0",
]
dev = [
    "pytest>=8.4.0",
    "ruff>=0.16.5",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
line-length = 79

[tool.ruff.lint]
select = ["D"]
extend-select = ["E501"]

[tool.ruff.lint.pydocstyle]
convention = "pep257"
